.TH ySCHED 7 2011-Aug "linux" "overview, objectives, and decision rationale"

.SH NAME
.B ySCHED
\- simple, elegant, and powerful kernighan scheduling grammar

.SH PATRON
.B eunomia-horae
(good order) goddess of law and appropriate time

.SH IMAGERY
beautiful, rose-bloomed maiden, sister of justice, peace, and fortune

.SH SUMMARY
ySCHED is a simple, elegant, powerful, and extended kernighan scheduling
grammar that builds on the classic cron implementation to enable support of
all schedule-based application (like calendaring).

.SH DOCUMENTATION
.nf
ySCHED (3)         application programming interface
.nf
ySCHED (5)         configuration, data, and files
.nf
ySCHED (7)   [***] overview, objectives, and decision rationale
